### PR TITLE
[JBEAP-18453] Import API sources

### PR DESCRIPTION
**Pull request by spyrkob**
Issue: https://issues.redhat.com/browse/JBEAP-18453

@fjuma I had to do a bit of hack with recompiling implementation sources instead of simply using dependency on the impl jar to maintain the generated OSGI manifest. Let me know if that's what you had in mind

### CODE REVIEW

**Comment by fjuma** [comment]
Thanks, @spyrkob! Will take a look at this tomorrow.

**Comment by fjuma** [comment]
@spyrkob Thanks very much for working on this. I think it looks good. I also did a quick sanity check to make sure that `jboss-jsf-api_2.3_spec-3.0.0.SP02-SNAPSHOT-sources.jar`, the `jboss-jsf-api_2.3_spec-3.0.0.SP02-SNAPSHOT-javadoc.jar`, and `jboss-jsf-api_2.3_spec-3.0.0.SP02-SNAPSHOT.jar` have the same number of files as before this change. I think you can go ahead and merge this when you're ready.

**Comment by spyrkob** [comment]
Thanks for review @fjuma :)

I don't have push permissions on the jboss-jakarta-faces-api repo. Could you merge the PR when you've got a moment?

**Comment by fjuma** [comment]
@spyrkob Sure, I'll merge now. Scott is on PTO today but I'll ask him on Monday to give SET commit access to this repo as well.

**Pull request merged**
